### ISSUE TITLE
Unsafe object access

### ISSUE THREAD

**Issue by riston** [argoroots/helpific#1]
Accessing nested object via dot or bracket notation could easily lead to TypeError where the object is not existing.

It is important because the slight change in the response API breaks the application.

The object access must be guarded before the access `a && a.b && a.b.c || "default"`. Instead of guarding the access use the module called [object-path](https://github.com/mariocasciaro/object-path), which does the same thing.

Instead of this:

```
if(properties['pretitle'].values) page.pretitle = properties['pretitle'].values[0].db_value
```

Use this, when the values do not exist the default value is returned:

```
var O = require('object-path');
page.pretitle = O.get(properties, "pretitle.values.0.db_value", "Default value")
```

**Comment by mitselek** [comment]
thanks-a-lot!

## 

Mihkel Putrinš
☎ +372 5656 0978

**Comment by argoroots** [comment]
Done in 3d430bd71f04202aaefb9ce55ebc78574b4b1404

Thanks!
