### ISSUE TITLE
Optimize front page image

### ISSUE THREAD

**Issue by riston** [argoroots/helpific#2]
The size of front image is too large ~818kB, by lowering resolution and quality the total size should be about ~300kB. (https://github.com/argoroots/helpific/blob/master/public/images/tom.jpg)

![tom](https://cloud.githubusercontent.com/assets/782237/9068519/9656bc0c-3aec-11e5-8adf-7cece66617fc.jpg)

**Comment by argoroots** [comment]
Fixed in 327ee15c5c50a0e1fe3c429b9de8a123c24a3bc8
